# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Claude Fable 5
    provider: openai
    model: anthropic/claude-fable-5-free
    apiKey: sk-ai-v1-9431885743998bd07fde966f0cfe965ddab59ea47161994c608fcb77de4b650a
    apiBase: https://zenmux.ai/api/v1
    roles:
      - chat
      - edit
      - autocomplete

